// Static analytics data for Netlify deployment
export const staticAnalyticsData = {
  summary: {
    totalDistricts: 1097,
    totalAuthentications: 3932847562,
    anomalyCount: 55,
    avgQDI: 0.48,
    criticalSurge: 110,
    elevatedSurge: 549,
    normalSurge: 438,
    needsAudit: 191,
    highLoad: 183,
    moderateLoad: 548,
    optimalLoad: 366,
    criticalPriority: 82,
    highPriority: 274,
    mediumPriority: 411,
  },
  qdiStats: {
    critical: 27,
    concern: 164,
    watch: 357,
    good: 549,
  },
  topAnomalies: [
    { state: "Uttar Pradesh", district: "Lucknow", severity: 0.89, totalAuth: 245678901 },
    { state: "Maharashtra", district: "Mumbai", severity: 0.85, totalAuth: 198765432 },
    { state: "Bihar", district: "Patna", severity: 0.82, totalAuth: 156789012 },
    { state: "West Bengal", district: "Kolkata", severity: 0.79, totalAuth: 143210987 },
    { state: "Tamil Nadu", district: "Chennai", severity: 0.76, totalAuth: 134567890 },
    { state: "Karnataka", district: "Bangalore Urban", severity: 0.73, totalAuth: 123456789 },
    { state: "Gujarat", district: "Ahmedabad", severity: 0.71, totalAuth: 112345678 },
    { state: "Rajasthan", district: "Jaipur", severity: 0.68, totalAuth: 101234567 },
    { state: "Madhya Pradesh", district: "Bhopal", severity: 0.65, totalAuth: 98765432 },
    { state: "Andhra Pradesh", district: "Hyderabad", severity: 0.62, totalAuth: 87654321 },
  ],
  topSurge: [
    { state: "Uttar Pradesh", district: "Varanasi", surgeScore: 4.2, avgDemand: 125000, peakDemand: 380000, growthRate: 0.35 },
    { state: "Maharashtra", district: "Pune", surgeScore: 3.9, avgDemand: 118000, peakDemand: 356000, growthRate: 0.32 },
    { state: "Bihar", district: "Muzaffarpur", surgeScore: 3.7, avgDemand: 95000, peakDemand: 312000, growthRate: 0.28 },
    { state: "West Bengal", district: "Howrah", surgeScore: 3.5, avgDemand: 89000, peakDemand: 289000, growthRate: 0.26 },
    { state: "Tamil Nadu", district: "Coimbatore", surgeScore: 3.3, avgDemand: 82000, peakDemand: 267000, growthRate: 0.24 },
    { state: "Karnataka", district: "Mysore", surgeScore: 3.1, avgDemand: 76000, peakDemand: 245000, growthRate: 0.22 },
    { state: "Gujarat", district: "Surat", surgeScore: 2.9, avgDemand: 71000, peakDemand: 223000, growthRate: 0.20 },
    { state: "Rajasthan", district: "Jodhpur", surgeScore: 2.7, avgDemand: 65000, peakDemand: 198000, growthRate: 0.18 },
    { state: "Madhya Pradesh", district: "Indore", surgeScore: 2.5, avgDemand: 59000, peakDemand: 176000, growthRate: 0.16 },
    { state: "Punjab", district: "Ludhiana", surgeScore: 2.3, avgDemand: 54000, peakDemand: 154000, growthRate: 0.14 },
  ],
  stateData: [
    { state: "Uttar Pradesh", totalAuth: 456789012, districts: 75, anomalies: 12, avgQDI: 0.52, criticalSurge: 15 },
    { state: "Maharashtra", totalAuth: 398765432, districts: 36, anomalies: 8, avgQDI: 0.48, criticalSurge: 11 },
    { state: "Bihar", totalAuth: 287654321, districts: 38, anomalies: 7, avgQDI: 0.55, criticalSurge: 9 },
    { state: "West Bengal", totalAuth: 234567890, districts: 23, anomalies: 5, avgQDI: 0.46, criticalSurge: 7 },
    { state: "Madhya Pradesh", totalAuth: 212345678, districts: 52, anomalies: 6, avgQDI: 0.51, criticalSurge: 8 },
    { state: "Tamil Nadu", totalAuth: 198765432, districts: 38, anomalies: 4, avgQDI: 0.42, criticalSurge: 6 },
    { state: "Rajasthan", totalAuth: 187654321, districts: 33, anomalies: 5, avgQDI: 0.49, criticalSurge: 7 },
    { state: "Karnataka", totalAuth: 176543210, districts: 31, anomalies: 3, avgQDI: 0.44, criticalSurge: 5 },
    { state: "Gujarat", totalAuth: 165432109, districts: 33, anomalies: 3, avgQDI: 0.45, criticalSurge: 6 },
    { state: "Andhra Pradesh", totalAuth: 154321098, districts: 26, anomalies: 2, avgQDI: 0.43, criticalSurge: 4 },
    { state: "Odisha", totalAuth: 143210987, districts: 30, anomalies: 3, avgQDI: 0.47, criticalSurge: 5 },
    { state: "Telangana", totalAuth: 132109876, districts: 33, anomalies: 2, avgQDI: 0.41, criticalSurge: 4 },
    { state: "Kerala", totalAuth: 121098765, districts: 14, anomalies: 1, avgQDI: 0.38, criticalSurge: 2 },
    { state: "Jharkhand", totalAuth: 110987654, districts: 24, anomalies: 2, avgQDI: 0.53, criticalSurge: 4 },
    { state: "Assam", totalAuth: 98765432, districts: 35, anomalies: 2, avgQDI: 0.50, criticalSurge: 3 },
  ],
  monthlyTrend: [
    { month: "Mar", demand: 280000, predicted: 275000 },
    { month: "Apr", demand: 320000, predicted: 315000 },
    { month: "May", demand: 380000, predicted: 370000 },
    { month: "Jun", demand: 420000, predicted: 410000 },
    { month: "Jul", demand: 480000, predicted: 465000 },
    { month: "Aug", demand: 520000, predicted: 510000 },
    { month: "Sep", demand: 580000, predicted: 570000 },
    { month: "Oct", demand: 640000, predicted: 625000 },
    { month: "Nov", demand: 700000, predicted: 690000 },
    { month: "Dec", demand: 750000, predicted: 745000 },
  ],
  anomalyByState: [
    { state: "Uttar Pradesh", count: 12 },
    { state: "Maharashtra", count: 8 },
    { state: "Bihar", count: 7 },
    { state: "Madhya Pra...", count: 6 },
    { state: "West Bengal", count: 5 },
    { state: "Rajasthan", count: 5 },
    { state: "Tamil Nadu", count: 4 },
    { state: "Karnataka", count: 3 },
  ],
  attentionDistricts: [
    { state: "Uttar Pradesh", district: "Varanasi", priorityScore: 92, priorityLevel: "Critical", surgeLevel: "Critical", qdiStatus: "Concern", loadStatus: "High", recommendation: "Immediate capacity expansion needed" },
    { state: "Maharashtra", district: "Pune", priorityScore: 88, priorityLevel: "Critical", surgeLevel: "Critical", qdiStatus: "Watch", loadStatus: "High", recommendation: "Deploy additional biometric devices" },
    { state: "Bihar", district: "Muzaffarpur", priorityScore: 85, priorityLevel: "Critical", surgeLevel: "Critical", qdiStatus: "Concern", loadStatus: "High", recommendation: "Technical audit recommended" },
    { state: "West Bengal", district: "Howrah", priorityScore: 82, priorityLevel: "Critical", surgeLevel: "Elevated", qdiStatus: "Watch", loadStatus: "Moderate", recommendation: "Monitor closely for surge" },
    { state: "Tamil Nadu", district: "Coimbatore", priorityScore: 79, priorityLevel: "High", surgeLevel: "Elevated", qdiStatus: "Good", loadStatus: "Moderate", recommendation: "Preventive maintenance" },
    { state: "Karnataka", district: "Mysore", priorityScore: 76, priorityLevel: "High", surgeLevel: "Elevated", qdiStatus: "Watch", loadStatus: "Moderate", recommendation: "Staff training needed" },
    { state: "Gujarat", district: "Surat", priorityScore: 73, priorityLevel: "High", surgeLevel: "Elevated", qdiStatus: "Good", loadStatus: "Moderate", recommendation: "Optimize queue management" },
    { state: "Rajasthan", district: "Jodhpur", priorityScore: 70, priorityLevel: "High", surgeLevel: "Elevated", qdiStatus: "Watch", loadStatus: "Moderate", recommendation: "Increase operational hours" },
    { state: "Madhya Pradesh", district: "Indore", priorityScore: 67, priorityLevel: "High", surgeLevel: "Normal", qdiStatus: "Good", loadStatus: "Optimal", recommendation: "Continue monitoring" },
    { state: "Punjab", district: "Ludhiana", priorityScore: 64, priorityLevel: "High", surgeLevel: "Normal", qdiStatus: "Good", loadStatus: "Optimal", recommendation: "Standard operations" },
    { state: "Haryana", district: "Gurgaon", priorityScore: 61, priorityLevel: "High", surgeLevel: "Normal", qdiStatus: "Good", loadStatus: "Optimal", recommendation: "No immediate action" },
    { state: "Uttarakhand", district: "Dehradun", priorityScore: 58, priorityLevel: "Medium", surgeLevel: "Normal", qdiStatus: "Good", loadStatus: "Optimal", recommendation: "Routine check" },
    { state: "Chhattisgarh", district: "Raipur", priorityScore: 55, priorityLevel: "Medium", surgeLevel: "Normal", qdiStatus: "Good", loadStatus: "Optimal", recommendation: "Stable operations" },
    { state: "Jharkhand", district: "Ranchi", priorityScore: 52, priorityLevel: "Medium", surgeLevel: "Normal", qdiStatus: "Good", loadStatus: "Optimal", recommendation: "No concerns" },
    { state: "Odisha", district: "Bhubaneswar", priorityScore: 49, priorityLevel: "Medium", surgeLevel: "Low", qdiStatus: "Good", loadStatus: "Optimal", recommendation: "Excellent performance" },
  ],
  policyBriefs: [
    { id: 1, title: "Critical Surge Alert", description: "110 districts experiencing critical demand surge requiring immediate capacity expansion", severity: "critical", icon: "alert" },
    { id: 2, title: "Quality Drift Warning", description: "191 districts need technical audit due to unusual biometric/demographic ratios", severity: "warning", icon: "quality" },
    { id: 3, title: "Anomaly Detection", description: "55 districts flagged by ML model with behavioral anomalies", severity: "info", icon: "anomaly" },
    { id: 4, title: "High Load Districts", description: "183 districts under high load, 548 moderate - resource reallocation recommended", severity: "warning", icon: "load" },
    { id: 5, title: "Priority Action Required", description: "82 critical and 274 high priority districts need immediate intervention", severity: "critical", icon: "priority" },
  ],
};
